### ISSUE TITLE
Entry Alert

### ISSUE THREAD

**Issue by jjv360** [jjv360/vatom-spaces-entry-alert#1]
Shows a toast and a sound when users enter a space.

---

### Tasks

- [x] Create plugin
- [x] Update plugin bridge with onEnter() event
- [x] Create icon and metadata
- [x] Publish to marketplace

**Comment by jjv360** [comment]
I thought I had done the bridge update, but it's not in the code and there's no PR...

**Comment by jjv360** [comment]
Actually this is already in production
